### ISSUE TITLE
paddle ssld pretrained model to pytorch

### ISSUE THREAD

**Issue by seefun** [SWHL/PPLCNet2PyTorch#2]
有计划迁移更多paddlpaddle的SSLD预训练模型到pytorch吗？ 比如服务端resnet，res2net系列，以及移动端MobileNet系列

**Comment by SWHL** [comment]
- 近期没有，不过你可以参考一下：[PaddleOCR2Pytorch](https://github.com/frotms/PaddleOCR2Pytorch) 这个项目中做的迁移动作较多一些
